version: "3.9"
services:
  service-a:
    build: service-a
    env_file: .env.dev
    command: "sleep $SLEEP_TIME"

  service-b:
    build: 
      args: # available just during build
          ANIMAL: big dog
          TOKEN: ${TOKEN}
    environment: # available during execution
      KEY: ${KEY}
