FROM alpine:3.14

ARG ANIMAL
ARG TOKEN
ENV KEY 1

RUN echo "Oh dang look at that $ANIMAL"
RUN echo "This is my token $TOKEN"
RUN echo "And this is my key $KEY"
RUN echo "Are we in production? $PRODUCTION"


CMD ["sleep", "9999"]
